const pablicInfo = [
    {
        id: `graphTarget0`,
        img: "./img/dog.png",
        date: "16.06.17",
        time: "16:20",
        status: 1,
        denotationImg: "./img/dog.png",
        denotationName: 'Бот Максим',
        type: "Инфо пост",
        price: "3 120 р",
        likes: 10,
        shares: 17,
        comments: 104,
        subscribe: 2875,
        malePopulation: 20,
        femalePopulation: 80,
        age: "17",
        cpa: "2.6 р.",

    },
    {
        id: `graphTarget1`,
        img: "",
        time: "16.06.17",
        time: "16:20",
        status: 0,
        denotation: "5421",
        type: "2011/04/25",
        price: "3 120 р.",
        subscribe: 3400,
        malePopulation: 20,
        femalePopulation: 80,
        age: "17",
        cpa: "",

    },
    {
        id: `graphTarget2`,
        img: "",
        time: "16.06.17",
        time: "16:20",
        status: "",
        denotation: "5421",
        type: "2011/04/25",
        price: "3 120 р.",
        subscribe: 666,
        malePopulation: 20,
        femalePopulation: 80,
        age: "17",
        cpa: "8.6 р.",
    },
    {
        id: `graphTarget3`,
        img: "./img/dog.png",
        date: "16.06.17",
        time: "16:20",
        status: 1,
        denotationImg: "./img/dog.png",
        denotationName: 'Бот Максим',
        type: "Инфо пост",
        price: "3 120 р",
        likes: 10,
        shares: 17,
        comments: 104,
        subscribe: 2875,
        malePopulation: 20,
        femalePopulation: 80,
        age: "17",
        cpa: "2.6 р.",

    },
]

export default pablicInfo;